### ISSUE TITLE
Replay analysis not work in Win10 ?

### ISSUE THREAD

**Issue by mtmzorro** [anmonite/wows-stats-plus#12]
Hello, I have install on win10, and my node version is LST 10.15.0.
I try to drag&drop `.wowsreplay` into the browser which opened by `view_chrome.bat`. But not work.
Then I opened the replay file by `WorldOfWarships.exe`, and there still info that `Now not in battle. Please wait until starting new battle.`

**Comment by anmonite** [comment]
Thanks for using my app.

Though I have heard Win10 related issue from several users, I have never changed my development environment to Win10. So I can't trace the root of this issue.

Perhaps, this issue comes from the "package.json" path resolution problem of Node.js npm on Win10.
This guess is brought by the log message from some users in the window of "bat" command prompt.

FYI, someone tried to execute install.bat and save the settings. After that, the issue was solved.
But I don't know this case is same to your case.

Please wait several weeks to investigate Win10 related issues.

**Comment by anmonite** [comment]
In addition, if you made modification of replay file settings by using "replay tool" or editing  "engine_config.xml", the current version of my app can not handling of this feature.

**Comment by mtmzorro** [comment]
Thanks for reply, the random battle works good for now in Win10, and I didn't use `replay tool` or editing `engine_config.xml`.

**Comment by anmonite** [comment]
Does "the random battle works good for now in Win10" you said mean the problem you reported is solved before you knew it?

**Comment by mtmzorro** [comment]
No, the replay file analysis still not working, but random battle mode player analysis working on Win10.

**Comment by mtmzorro** [comment]
I did some test after giving you the report in Win10.

```
Random battle works.

Replay file drag&drop into browser not work.

Replay file open by WorldOfWarships.exe not work.
```

Looks like the app is watching tempArenaInfo.json change in `gameFolder/replays`.

And I noticed that this file was not created when I opend the replay file by WorldOfWarships.exe.

I hope this information will help you a little.

Thanks again.

**Comment by anmonite** [comment]
Thank you for trying and reporting several situation.

I knew you tried wrong method to use my app.
You need to drag&drop .wowsreplay file to the icon of view_chrome.bat directly, not to browser window.

And then, my app does not work when you opened the replay file by WorldOfWarships.exe.
Because the replay mode of WoWs client does not create '/replays/tempArenaInfo.json' and my app is polling it to detect the battle.

Do you check these point?

**Comment by mtmzorro** [comment]
Unfortunately, still not work in Win10. 
I drag&drop .wowsreplay file to the icon of view_chrome.bat directly, then the node cmd window open shortly and auto close by itself. And the browser window shown `ERR_CONNECTION_REFUSED`.

And I also tried to execute install.bat and save the settings again, but still not working.

After that, I analyz replay files in win7. This is already met my needs. 

Thanks. (*^▽^*)
